# Services for PostgreSQL with WAL
apiVersion: v1
kind: Service
metadata:
  name: postgres-wal
  labels:
    app: postgres-wal
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres-wal

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-wal-external
  labels:
    app: postgres-wal
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres-wal