# ClusterIP Service for Internal Access to PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres

---
# LoadBalancer Service for External Access to PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: postgres